const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  minimize: () => ipcRenderer.send('window-minimize'),
  maximize: () => ipcRenderer.send('window-maximize'),
  close: () => ipcRenderer.send('window-close'),
  selectImage: () => ipcRenderer.invoke('select-image'),
  selectMultipleImages: () => ipcRenderer.invoke('select-multiple-images'),
  selectVideo: () => ipcRenderer.invoke('select-video'),
  saveFile: (path) => ipcRenderer.invoke('save-file', path),
  openURL: (url) => ipcRenderer.send('open-url', url),
  downloadUpdate: (url) => ipcRenderer.invoke('download-update', url),
  installUpdate: (filePath) => ipcRenderer.invoke('install-update', filePath),
  onDownloadProgress: (callback) => ipcRenderer.on('download-progress', (event, data) => callback(data)),
  getRuntimeMeta: () => ipcRenderer.invoke('get-runtime-meta'),
  restartBackend: () => ipcRenderer.invoke('restart-backend'),
  publishMoment: (data) => ipcRenderer.invoke('publish-moment', data),
  deleteScript: (id) => ipcRenderer.invoke('delete-script', id),
  updateScript: (id, data) => ipcRenderer.invoke('update-script', { id, ...data }),
  addScript: (data) => ipcRenderer.invoke('add-script', data),
  getScripts: () => ipcRenderer.invoke('get-scripts'),
  getFileSize: (path) => ipcRenderer.invoke('get-file-size', path),
  getThumbnail: (path, maxWidth) => ipcRenderer.invoke('get-thumbnail', path, maxWidth),
  compressImage: (path) => ipcRenderer.invoke('compress-image', path),

  // ── AI 创意中心 ──
  aiChat: (data) => ipcRenderer.invoke('ai-chat', data),
  aiGenerateImage: (data) => ipcRenderer.invoke('ai-generate-image', data),
  aiCreateVideoTask: (data) => ipcRenderer.invoke('ai-create-video-task', data),
  aiPollVideoTask: (data) => ipcRenderer.invoke('ai-poll-video-task', data),
  aiAbort: () => ipcRenderer.invoke('ai-abort'),
  aiGetConfig: () => ipcRenderer.invoke('ai-get-config'),
  aiSaveConfig: (data) => ipcRenderer.invoke('ai-save-config', data),
  selectReferenceImage: () => ipcRenderer.invoke('select-reference-image'),
});
